---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "deluan/navidrome:latest"
    pull: yes
    labels:
      "flame.type": "application"
      "flame.name": "Jellyfin"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    state: "started"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VIRTUAL_HOST": "navidrome.home"
      "ScanSchedule": "@every 24h"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/data"
      - "/media/Media/Music:/music"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: always
    ports:
      - 4533:4533
    exposed_ports:
      - 8096
