---

- hosts: pi
  become: yes
  vars_files:
    - vars/default.yml
    - vars/secrets.yml
  roles: 
    - role: docker
    - role: containers/deluge
    - role: containers/jackett
    - role: containers/lidarr
    - role: containers/sonarr
    - role: containers/radarr
    - role: containers/readarr
    - role: containers/prowlarr
    - role: containers/jellyfin
    - role: containers/navidrome
    - role: containers/wireguard
    - role: containers/nextcloud
