---

- hosts: tera
  become: yes
  vars_files:
    - vars/default.yml
    - vars/secrets.yml
  roles: 
    - role: docker
    - role: backup_borg
    - role: containers/gitea
    - role: containers/deluge
    - role: containers/nginx-proxy
    - role: containers/dnsmasq
    - role: containers/jackett
    - role: containers/lidarr
    - role: containers/sonarr
    - role: containers/radarr
      # - role: containers/readarr
    - role: containers/prowlarr
    - role: containers/jellyfin
    - role: containers/navidrome
    - role: containers/wireguard
    # - role: containers/nextcloud
    - role: containers/mumble
    - role: containers/syncthing
