---

- hosts: pi
  become: yes
  vars_files:
    - vars/default.yml
    - vars/secrets.yml
  roles: 
    - role: containers/swag
    - role: docker
    - role: containers/deluge
    - role: containers/jackett
    - role: containers/sonarr
    - role: containers/radarr
    - role: containers/jellyfin
    - role: homer
