---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "mumblevoip/mumble-server:latest"
    pull: yes
    user: "1000:1000"
    labels:
      "flame.type": "application"
      "flame.name": "{{ container_name }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    state: "started"
    env:
      "PUID": "1000"
      "PGID": "1000"
      "TZ": "{{ timezone }}"
      "VIRTUAL_HOST": "{{ container_name }}.box"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/data"
      - "/media/Media/Music:/music"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: always
    ports:
      - 64738:64738
    exposed_ports:
      - 64738
