---
- name: FTP
  docker_container:
    name: ftp
    env:
      USERS: "kyle|kyle|/home/kyle"
      ADDRESS: "{{ wireguard_host }}"
    image: delfer/alpine-ftp-server
    volumes:
      - "/media/kyle:/home/kyle"
    ports:
      - "2021:21"
      - "21000-21010:21000-21010"
    restart_policy: always
