---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/plex:latest"
    pull: yes
    privileged: yes
    devices:
      - "/dev/video10:/dev/video10"
      - "/dev/video11:/dev/video11"
      - "/dev/video12:/dev/video12"
    state: "started"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
      "VIRTUAL_HOST": "plex.box"
      "VIRTUAL_PORT": "32400"
      "PLEX_CLAIM": "claim-A39HXqQcim41PnrZzxV1"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "/media/Media/TV:/tv"
      - "/media/_slow/Media/Transcodes:/config/data/transcodes"
      - "/media/Media/Metadata:/metadata"
      - "/media/Media/Cache:/cache"
      - "/media/Media/Movies:/movies"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: always
    ports:
      - 32400:32400
    exposed_ports:
      - 32400
