---
- name: Ensure Media directory exists
  file:
    path: "/home/{{ username }}/Media/TV"
    state: directory
    mode: "0755"
    owner: "{{ username }}"

- name: Ensure Downloads directory exists
  file:
    path: "/home/{{ username }}/Downloads"
    state: directory
    mode: "0755"
    owner: "{{ username }}"

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "linuxserver/sonarr:latest"
    pull: yes
    labels:
      "flame.type": "application"
      "flame.name": "{{ container_name | title }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "/home/{{ username }}/Media/TV:/tv"
      - "/home/{{ username }}/Downloads/TV:/downloads"
    restart_policy: unless-stopped
    ports:
      - 8989:8989

- name: Add {{ container_name }} to the SWAG network (reverse-proxy)
  docker_network:
    name: swag_network
    connected:
      - sonarr
    appends: yes
  when: enable_swag
