---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/jellyfin"
    pull: yes
    privileged: yes
    labels:
      "flame.type": "application"
      "flame.name": "{{ dashboard_name }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    devices:
      - "/dev/video10:/dev/video10"
      - "/dev/video11:/dev/video11"
      - "/dev/video12:/dev/video12"
    state: "started"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
      "VIRTUAL_HOST": "jellyfin.box"
      "VIRTUAL_PORT": "8096"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "/media/Media/TV:/data/TV"
      - "/media/_slow/Media/Transcodes:/config/data/transcodes"
      - "/media/Media/Metadata:/metadata"
      - "/media/Media/Cache:/data/Cache"
      - "/media/Media/Movies:/data/Movies"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: always
    ports:
      - 8096:8096
    exposed_ports:
      - 8096
