---

- name: Setup AUR and AUR packages
  hosts: all
  tasks: 

    - name: Install yay using makepkg if it isn't installed already
      kewlfft.aur.aur:
        name: yay
        use: makepkg
        state: present
      become: yes

  - name: Install aur packages
    kewlfft.aur.aur:
      use: yay
      name:
        - package_name_1
        - package_name_2
