---
- name: Setup Arch System
  hosts: all
  become: yes
  tasks: 
    - name: Sync with repos
      community.general.pacman:
        update_cache: yes
        upgrade: yes

    - name: Install packages
      community.general.pacman:
        name: 
          - neovim
          - git
          - go
          - go-tools
          - ripgrep
          - base-devel
          - docker
          - fzf 
          - man
          - python-pip
          - python-pynvim
          - ripgrep 
          - sudo 
          - tmux
          - zsh 
          - zsh-syntax-highlighting
        state: present
