---
- name: Install packages with pacman
  hosts: all
  become: yes
  vars_files:
    - packages.txt
  tasks: 
    - name: Sync with repos
      community.general.pacman:
        update_cache: yes
        upgrade: yes

    - name: Install packages
      community.general.pacman:
        name: "{{ packages }}"
        state: present
