---
- name: Setup dotfiles and other basic config
  hosts: all
  tasks:
    - name: Pull dotfiles from git
      ansible.builtin.git:
        repo: 'https://gitlab.com/adavenport/dotfiles.git'
        dest: ~/dotfiles
        clone: yes
        update: yes

    - name: Create .config directory
      ansible.builtin.file:
        path: ~/.config
        state: directory

    - name: Link nvim
      ansible.builtin.file:
        src: ~/dotfiles/.config/nvim
        dest: ~/.config/nvim
        state: link

    - name: Get vim plug
      command: "sh -c 'curl -fLo \"${XDG_DATA_HOME:-$HOME/.local/share}\"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'"

    - name: Vim Plugin Update
      command: "nvim --headless +PlugInstall +qall"

    - name: Link zsh
      ansible.builtin.file:
        src: ~/dotfiles/.zshrc
        dest: ~/.zshrc
        state: link

    - name: Change to zsh
      become: yes
      user:
        name: "adam"
        shell: /bin/zsh


