---
- name: Setup dotfiles and other basic config
  hosts: all
  tasks:

    - name: Pull dotfiles from git
      ansible.builtin.git:
        repo: 'https://gitlab.com/adavenport/dotfiles.git'
        dest: ~/dotfiles
        clone: yes
        update: yes

    - name: Create .config directory
      ansible.builtin.file:
        path: ~/.config
        state: directory

    - name: Link nvim
      ansible.builtin.file:
        src: ~/dotfiles/.config/nvim
        dest: ~/.config/nvim
        state: link

    - name: Link tmux
      ansible.builtin.file:
        src: ~/dotfiles/.
        dest: ~/.config/nvim
        state: link

    - name: Link zsh
      ansible.builtin.file:
        src: ~/dotfiles/.zshrc
        dest: ~/.zshrc
        state: link

    - name: Check for vim plug
      ansible.builtin.stat:
        path: ~/.local/share/nvim/site/autoload/plug.vim
      register: plug

    - name: Get vim plug
      command: "sh -c 'curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'"
      when: not plug.stat.exists

    - name: Vim Plugin Install
      command: "nvim --headless +PlugUpdate +qall"

    - name: Change to zsh
      become: yes
      user:
        name: "adam"
        shell: /bin/zsh


