---
- name: Ensure Media directory exists
  file:
    path: "/media/Media/Movies"
    state: directory
    mode: "0755"
    owner: "{{ username }}"

- name: Ensure Downloads directory exists
  file:
    path: "/media/Downloads"
    state: directory
    mode: "0755"
    owner: "{{ username }}"

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/radarr"
    pull: yes
    labels:
      "flame.type": "application"
      "flame.name": "{{ container_name | title }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ docker_dir }}/deluge/data:/data"
      - "/media/Media/Movies:/movies"
      - "/media/Downloads/TV:/downloads"
      - "/tank/Downloads:/downloads"
    restart_policy: always
    ports:
      - 7878:7878

