---
- name: Ensure Media directory exists
  file:
    path: "/media/Media/Music"
    state: directory
    mode: "0755"
    owner: "{{ username }}"

- name: Ensure Downloads directory exists
  file:
    path: "/media/Downloads"
    state: directory
    mode: "0755"
    owner: "{{ username }}"

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "linuxserver/lidarr:latest"
    pull: yes
    labels:
      "flame.type": "application"
      "flame.name": "{{ container_name | title }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VIRTUAL_HOST": "lidarr.box"
      "VIRTUAL_PORT": "8989"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ docker_dir }}/deluge/data:/data"
      - "/media/Media/Music:/music"
      - "/media/Downloads/TV:/downloads"
    restart_policy: always
    ports:
      - 8686:8686
    exposed_ports:
      - 8096

